### ISSUE TITLE
.env

### ISSUE THREAD

**Issue by xiuwf** [dairoot/ChatGPT-Mirror#5]
不好意思问个蠢问题，.env在哪里？

Failed to load .env file ".env": Error: ENOENT: no such file or directory, open '.env'
    at Object.openSync (node:fs:573:18)
    at Object.readFileSync (node:fs:452:35)
    at tryLoadDotEnv (/app/worker/node_modules/wrangler/wrangler-dist/cli.js:159135:72)
    at loadDotEnv (/app/worker/node_modules/wrangler/wrangler-dist/cli.js:159144:12)
    at /app/worker/node_modules/wrangler/wrangler-dist/cli.js:201234:20
    at /app/worker/node_modules/wrangler/wrangler-dist/cli.js:165907:16
    at maybeAsyncResult (/app/worker/node_modules/wrangler/wrangler-dist/cli.js:164128:44)
    at /app/worker/node_modules/wrangler/wrangler-dist/cli.js:165906:14
    at /app/worker/node_modules/wrangler/wrangler-dist/cli.js:164115:22
    at Array.reduce (<anonymous>) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '.env'

**Comment by dairoot** [comment]
删除volume, 重新试下 `docker volume rm chatgpt-mirror_chatgpt_data`
